package router

import (
	"app/index/indexIndex"

	"github.com/labstack/echo/v4"
)

func IndexIndexRouter(e *echo.Echo) {
	/*Ad*/
	e.GET("/ad/index", indexIndex.AdIndex)
	/*Article*/
	e.GET("/article/index", indexIndex.ArticleIndex)
	e.GET("/article/list", indexIndex.ArticleList)
	e.GET("/article/show", indexIndex.ArticleShow)
	/*Bankcard*/
	e.GET("/bankcard/index", indexIndex.BankcardIndex)
	e.GET("/bankcard/list", indexIndex.BankcardList)
	e.GET("/bankcard/show", indexIndex.BankcardShow)
	e.GET("/bankcard/my", indexIndex.BankcardMy)
	e.GET("/bankcard/add", indexIndex.BankcardAdd)
	e.POST("/bankcard/save", indexIndex.BankcardSave)
	e.GET("/bankcard/status", indexIndex.BankcardStatus)
	e.GET("/bankcard/delete", indexIndex.BankcardDelete)
	/*City*/
	e.GET("/city/index", indexIndex.CityIndex)
	/*Coupon*/
	e.GET("/coupon/index", indexIndex.CouponIndex)
	e.GET("/coupon/list", indexIndex.CouponList)
	e.GET("/coupon/show", indexIndex.CouponShow)
	/*CouponUser*/
	e.GET("/coupon_user/index", indexIndex.CouponUserIndex)
	e.GET("/coupon_user/list", indexIndex.CouponUserList)
	e.GET("/coupon_user/show", indexIndex.CouponUserShow)
	e.GET("/coupon_user/my", indexIndex.CouponUserMy)
	e.GET("/coupon_user/add", indexIndex.CouponUserAdd)
	e.POST("/coupon_user/save", indexIndex.CouponUserSave)
	e.GET("/coupon_user/status", indexIndex.CouponUserStatus)
	e.GET("/coupon_user/delete", indexIndex.CouponUserDelete)
	/*Crontab*/
	e.GET("/crontab/index", indexIndex.CrontabIndex)
	e.GET("/crontab/list", indexIndex.CrontabList)
	e.GET("/crontab/show", indexIndex.CrontabShow)
	/*District*/
	e.GET("/district/index", indexIndex.DistrictIndex)
	e.GET("/district/list", indexIndex.DistrictList)
	e.GET("/district/show", indexIndex.DistrictShow)
	/*Fav*/
	e.GET("/fav/index", indexIndex.FavIndex)
	e.GET("/fav/list", indexIndex.FavList)
	e.GET("/fav/show", indexIndex.FavShow)
	e.GET("/fav/my", indexIndex.FavMy)
	e.GET("/fav/add", indexIndex.FavAdd)
	e.POST("/fav/save", indexIndex.FavSave)
	e.GET("/fav/delete", indexIndex.FavDelete)
	/*Follow*/
	e.GET("/follow/index", indexIndex.FollowIndex)
	e.GET("/follow/list", indexIndex.FollowList)
	e.GET("/follow/show", indexIndex.FollowShow)
	e.GET("/follow/my", indexIndex.FollowMy)
	e.GET("/follow/add", indexIndex.FollowAdd)
	e.POST("/follow/save", indexIndex.FollowSave)
	e.GET("/follow/status", indexIndex.FollowStatus)
	e.GET("/follow/delete", indexIndex.FollowDelete)
	/*Friend*/
	e.GET("/friend/index", indexIndex.FriendIndex)
	e.GET("/friend/list", indexIndex.FriendList)
	e.GET("/friend/show", indexIndex.FriendShow)
	e.GET("/friend/my", indexIndex.FriendMy)
	e.GET("/friend/add", indexIndex.FriendAdd)
	e.POST("/friend/save", indexIndex.FriendSave)
	e.GET("/friend/delete", indexIndex.FriendDelete)
	/*FriendApply*/
	e.GET("/friend_apply/index", indexIndex.FriendApplyIndex)
	e.GET("/friend_apply/list", indexIndex.FriendApplyList)
	e.GET("/friend_apply/show", indexIndex.FriendApplyShow)
	e.GET("/friend_apply/my", indexIndex.FriendApplyMy)
	e.GET("/friend_apply/add", indexIndex.FriendApplyAdd)
	e.POST("/friend_apply/save", indexIndex.FriendApplySave)
	e.GET("/friend_apply/delete", indexIndex.FriendApplyDelete)
	/*GoldLog*/
	e.GET("/gold_log/index", indexIndex.GoldLogIndex)
	e.GET("/gold_log/list", indexIndex.GoldLogList)
	e.GET("/gold_log/show", indexIndex.GoldLogShow)
	e.GET("/gold_log/my", indexIndex.GoldLogMy)
	e.GET("/gold_log/add", indexIndex.GoldLogAdd)
	e.POST("/gold_log/save", indexIndex.GoldLogSave)
	e.GET("/gold_log/delete", indexIndex.GoldLogDelete)
	/*Guest*/
	e.GET("/guest/index", indexIndex.GuestIndex)
	e.GET("/guest/list", indexIndex.GuestList)
	e.GET("/guest/show", indexIndex.GuestShow)
	e.GET("/guest/my", indexIndex.GuestMy)
	e.GET("/guest/add", indexIndex.GuestAdd)
	e.POST("/guest/save", indexIndex.GuestSave)
	e.GET("/guest/status", indexIndex.GuestStatus)
	e.GET("/guest/delete", indexIndex.GuestDelete)
	/*Index*/
	e.GET("/index/index", indexIndex.IndexIndex)
	/*Invite*/
	e.GET("/invite/index", indexIndex.InviteIndex)
	e.GET("/invite/list", indexIndex.InviteList)
	e.GET("/invite/show", indexIndex.InviteShow)
	e.GET("/invite/my", indexIndex.InviteMy)
	e.GET("/invite/add", indexIndex.InviteAdd)
	e.POST("/invite/save", indexIndex.InviteSave)
	e.GET("/invite/delete", indexIndex.InviteDelete)
	/*InviteAccountLog*/
	e.GET("/invite_account_log/index", indexIndex.InviteAccountLogIndex)
	e.GET("/invite_account_log/list", indexIndex.InviteAccountLogList)
	e.GET("/invite_account_log/show", indexIndex.InviteAccountLogShow)
	e.GET("/invite_account_log/my", indexIndex.InviteAccountLogMy)
	e.GET("/invite_account_log/add", indexIndex.InviteAccountLogAdd)
	e.POST("/invite_account_log/save", indexIndex.InviteAccountLogSave)
	e.GET("/invite_account_log/delete", indexIndex.InviteAccountLogDelete)
	/*Login*/
	e.GET("/login/index", indexIndex.LoginIndex)
	e.POST("/login/save", indexIndex.LoginSave)
	e.POST("/login/findpwdsave", indexIndex.LoginFindpwdsave)
	e.GET("/login/sendsms", indexIndex.LoginSendsms)
	/*Love*/
	e.GET("/love/index", indexIndex.LoveIndex)
	e.GET("/love/list", indexIndex.LoveList)
	e.GET("/love/get", indexIndex.LoveGet)
	e.GET("/love/my", indexIndex.LoveMy)
	e.GET("/love/add", indexIndex.LoveAdd)
	e.POST("/love/save", indexIndex.LoveSave)
	e.GET("/love/delete", indexIndex.LoveDelete)
	/*Notice*/
	e.GET("/notice/index", indexIndex.NoticeIndex)
	e.GET("/notice/list", indexIndex.NoticeList)
	e.GET("/notice/show", indexIndex.NoticeShow)
	e.GET("/notice/my", indexIndex.NoticeMy)
	e.GET("/notice/add", indexIndex.NoticeAdd)
	e.POST("/notice/save", indexIndex.NoticeSave)
	e.GET("/notice/status", indexIndex.NoticeStatus)
	e.GET("/notice/delete", indexIndex.NoticeDelete)
	/*OpenAlipayMini*/
	e.GET("/open_alipay_mini/index", indexIndex.OpenAlipayMiniIndex)
	e.GET("/open_alipay_mini/list", indexIndex.OpenAlipayMiniList)
	e.GET("/open_alipay_mini/show", indexIndex.OpenAlipayMiniShow)
	/*OpenWxapp*/
	e.GET("/open_wxapp/index", indexIndex.OpenWxappIndex)
	e.GET("/open_wxapp/list", indexIndex.OpenWxappList)
	e.GET("/open_wxapp/show", indexIndex.OpenWxappShow)
	/*Openlogin*/
	e.GET("/openlogin/index", indexIndex.OpenloginIndex)
	e.GET("/openlogin/list", indexIndex.OpenloginList)
	e.GET("/openlogin/show", indexIndex.OpenloginShow)
	e.GET("/openlogin/my", indexIndex.OpenloginMy)
	e.GET("/openlogin/add", indexIndex.OpenloginAdd)
	e.POST("/openlogin/save", indexIndex.OpenloginSave)
	e.GET("/openlogin/delete", indexIndex.OpenloginDelete)
	/*PayLog*/
	e.GET("/pay_log/index", indexIndex.PayLogIndex)
	e.GET("/pay_log/list", indexIndex.PayLogList)
	e.GET("/pay_log/show", indexIndex.PayLogShow)
	e.GET("/pay_log/my", indexIndex.PayLogMy)
	e.GET("/pay_log/add", indexIndex.PayLogAdd)
	e.POST("/pay_log/save", indexIndex.PayLogSave)
	e.GET("/pay_log/delete", indexIndex.PayLogDelete)
	/*Pm*/
	e.GET("/pm/index", indexIndex.PmIndex)
	e.GET("/pm/list", indexIndex.PmList)
	e.GET("/pm/show", indexIndex.PmShow)
	e.GET("/pm/my", indexIndex.PmMy)
	e.GET("/pm/add", indexIndex.PmAdd)
	e.POST("/pm/save", indexIndex.PmSave)
	e.GET("/pm/status", indexIndex.PmStatus)
	e.GET("/pm/delete", indexIndex.PmDelete)
	/*Pv*/
	e.GET("/pv/index", indexIndex.PvIndex)
	e.GET("/pv/list", indexIndex.PvList)
	e.GET("/pv/show", indexIndex.PvShow)
	/*Recharge*/
	e.GET("/recharge/index", indexIndex.RechargeIndex)
	e.GET("/recharge/list", indexIndex.RechargeList)
	e.GET("/recharge/show", indexIndex.RechargeShow)
	e.GET("/recharge/my", indexIndex.RechargeMy)
	e.GET("/recharge/add", indexIndex.RechargeAdd)
	e.POST("/recharge/save", indexIndex.RechargeSave)
	e.GET("/recharge/status", indexIndex.RechargeStatus)
	e.GET("/recharge/delete", indexIndex.RechargeDelete)
	/*Sgpay*/
	e.GET("/sgpay/index", indexIndex.SgpayIndex)
	e.GET("/sgpay/list", indexIndex.SgpayList)
	e.GET("/sgpay/show", indexIndex.SgpayShow)
	e.GET("/sgpay/my", indexIndex.SgpayMy)
	e.GET("/sgpay/add", indexIndex.SgpayAdd)
	e.POST("/sgpay/save", indexIndex.SgpaySave)
	e.GET("/sgpay/status", indexIndex.SgpayStatus)
	e.GET("/sgpay/delete", indexIndex.SgpayDelete)
	/*TableData*/
	e.GET("/table_data/index", indexIndex.TableDataIndex)
	e.GET("/table_data/list", indexIndex.TableDataList)
	e.GET("/table_data/show", indexIndex.TableDataShow)
	e.GET("/table_data/my", indexIndex.TableDataMy)
	e.GET("/table_data/add", indexIndex.TableDataAdd)
	e.POST("/table_data/save", indexIndex.TableDataSave)
	e.GET("/table_data/status", indexIndex.TableDataStatus)
	e.GET("/table_data/delete", indexIndex.TableDataDelete)
	/*Tixian*/
	e.GET("/tixian/index", indexIndex.TixianIndex)
	e.GET("/tixian/list", indexIndex.TixianList)
	e.GET("/tixian/show", indexIndex.TixianShow)
	/*Upload*/
	e.POST("/upload/img", indexIndex.UploadImg)
	/*User*/
	e.GET("/user/index", indexIndex.UserIndex)
	e.GET("/user/set", indexIndex.UserSet)
	e.GET("/user/info", indexIndex.UserInfo)
	e.POST("/user/save", indexIndex.UserSave)
	e.POST("/user/telephonesave", indexIndex.UserTelephonesave)
	e.POST("/user/passwordsave", indexIndex.UserPasswordsave)
	e.POST("/user/paypwdsave", indexIndex.UserPaypwdsave)
	e.GET("/user/sendsms", indexIndex.UserSendsms)
	/*UserAddress*/
	e.GET("/user_address/index", indexIndex.UserAddressIndex)
	e.GET("/user_address/list", indexIndex.UserAddressList)
	e.GET("/user_address/show", indexIndex.UserAddressShow)
	e.GET("/user_address/my", indexIndex.UserAddressMy)
	e.GET("/userress/add", indexIndex.UserAddressAdd)
	e.POST("/user_address/save", indexIndex.UserAddressSave)
	e.GET("/user_address/status", indexIndex.UserAddressStatus)
	e.GET("/user_address/delete", indexIndex.UserAddressDelete)
	/*UserAuth*/
	e.GET("/user_auth/index", indexIndex.UserAuthIndex)
	e.GET("/user_auth/list", indexIndex.UserAuthList)
	e.GET("/user_auth/show", indexIndex.UserAuthShow)
	e.GET("/user_auth/my", indexIndex.UserAuthMy)
	e.GET("/user_auth/add", indexIndex.UserAuthAdd)
	e.POST("/user_auth/save", indexIndex.UserAuthSave)
	e.GET("/user_auth/status", indexIndex.UserAuthStatus)
	e.GET("/user_auth/delete", indexIndex.UserAuthDelete)
	/*UserBlack*/
	e.GET("/user_black/index", indexIndex.UserBlackIndex)
	e.GET("/user_black/list", indexIndex.UserBlackList)
	e.GET("/user_black/show", indexIndex.UserBlackShow)
	e.GET("/user_black/my", indexIndex.UserBlackMy)
	e.GET("/user_black/add", indexIndex.UserBlackAdd)
	e.POST("/user_black/save", indexIndex.UserBlackSave)
	e.GET("/user_black/delete", indexIndex.UserBlackDelete)
	/*register*/
	e.GET("/register/index", indexIndex.RegisterIndex)
	e.POST("/register/save", indexIndex.RegisterSave)
	e.GET("/register/sendsms", indexIndex.RegisterSendsms)

}
